//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrasscutterTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrasscutterTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 28010101: 黄金蟹
        ///28010102: 太阳蟹
        ///28010103: 海蓝蟹
        ///28010104: 将军蟹
        ///28010105: 薄红蟹
        ///28010106: 螃蟹
        ///28010201: 蓝角蜥
        ///28010202: 红角蜥
        ///28010203: 绿角蜥
        ///28010204: 落日鳅鳅
        ///28010205: 金鳅鳅
        ///28010206: 晴天鳅鳅
        ///28010207: 嗜髓蜥
        ///28010301: 青蛙
        ///28010302: 泥蛙
        ///28010303: 蓝蛙
        ///28010401: 藤纹陆鳗鳗
        ///28010402: 深海鳗鳗
        ///28010403: 赤鳍陆鳗鳗
        ///28020101: 雪狐
        ///28020102: 红狐
        ///28020103: 送礼雪狐
        ///28020104: 送大礼雪狐
        ///28020105: 雪狐
        ///28020106: 红狐
        ///28020201: 松鼠
        ///28020301: 野林猪
        ///28020302: 小野林猪
        ///28020303: 雪猪
        ///28020304: 「大雪猪王」
        ///28020305: 冰冻雪猪
        ///28020306: 雪猪
        ///28020307: 野林猪
        ///28020308: 冰冻雪猪
        ///28020309: 「大雪猪王」
        ///28020401: 北地犬
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Animal {
            get {
                return ResourceManager.GetString("Animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20513: 迷误者之灯
        ///20514: 迷误者之灯
        ///20523: 翠蔓的智者
        ///20524: 翠蔓的智者
        ///20533: 月桂的宝冠
        ///20534: 月桂的宝冠
        ///20543: 迷宫的游人
        ///20544: 迷宫的游人
        ///20553: 贤智的定期
        ///20554: 贤智的定期
        ///21513: 如蜜的盛宴
        ///21514: 如蜜的盛宴
        ///21523: 裁断的翎羽
        ///21524: 裁断的翎羽
        ///21533: 沙王的投影
        ///21534: 沙王的投影
        ///21543: 梦中的铁花
        ///21544: 梦中的铁花
        ///21553: 沉金的岁月
        ///21554: 沉金的岁月
        ///51110: 异国之盏
        ///51111: 异国之盏
        ///51112: 异国之盏
        ///51113: 异国之盏
        ///51114: 异国之盏
        ///51120: 归乡之羽
        ///51121: 归乡之羽
        ///51122: 归乡之羽
        ///51123: 归乡之羽
        ///51124: 归乡之羽
        ///51130: 感别之冠
        ///51131: 感别之冠
        ///51132: 感别之冠
        ///51133: 感别之冠
        ///51134: 感别之冠
        ///51140: 故人之心
        ///51141: 故人之心
        ///51142: 故人之心
        ///51143: 故人之心
        ///51144: 故人之心
        ///51150: 逐光之石
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Artifact {
            get {
                return ResourceManager.GetString("Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20: 深林的记忆
        ///21: 饰金之梦
        ///51: 行者之心
        ///52: 勇士之心
        ///53: 守护之心
        ///54: 奇迹
        ///55: 战狂
        ///56: 武人
        ///57: 教官
        ///58: 赌徒
        ///59: 流放者
        ///60: 冒险家
        ///61: 幸运儿
        ///62: 学士
        ///63: 游医
        ///71: 冰风迷途的勇士
        ///72: 平息鸣雷的尊者
        ///73: 渡过烈火的贤人
        ///74: 被怜爱的少女
        ///75: 角斗士的终幕礼
        ///76: 翠绿之影
        ///77: 流浪大地的乐团
        ///78: 冰之川与雪之砂
        ///79: 如雷的盛怒
        ///80: 炽烈的炎之魔女
        ///81: 昔日宗室之仪
        ///82: 染血的骑士道
        ///83: 祭火之人
        ///84: 祭水之人
        ///85: 祭雷之人
        ///86: 祭风之人
        ///87: 祭冰之人
        ///88: 悠古的磐岩
        ///89: 逆飞的流星
        ///90: 沉沦之心
        ///91: 千岩牢固
        ///92: 苍白之火
        ///93: 追忆之注连
        ///94: 绝缘之旗印
        ///95: 华馆梦醒形骸记
        ///96: 海染砗磲
        ///97: 辰砂往生录
        ///98: 来歆余响
        ///99: 高天的风之主 的本地化字符串。
        /// </summary>
        internal static string ArtifactCat {
            get {
                return ResourceManager.GetString("ArtifactCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10001: 生命值
        ///10002: 生命值百分比
        ///10003: 攻击力
        ///10004: 攻击力百分比
        ///10005: 防御力
        ///10006: 防御力百分比
        ///10007: 元素充能效率
        ///10008: 元素精通
        ///10009: 火元素抗性
        ///10010: 雷元素抗性
        ///10011: 冰元素抗性
        ///10012: 水元素抗性
        ///10013: 风元素抗性
        ///10014: 岩元素抗性
        ///10015: 草元素抗性
        ///12001: 攻击力
        ///13001: 生命值
        ///13002: 生命值百分比
        ///13003: 攻击力
        ///13004: 攻击力百分比
        ///13005: 防御力
        ///13006: 防御力百分比
        ///13007: 暴击率
        ///13008: 暴击伤害
        ///13009: 治疗加成
        ///13010: 元素精通
        ///14001: 生命值
        ///15001: 生命值
        ///15002: 生命值百分比
        ///15003: 攻击力
        ///15004: 攻击力百分比
        ///15005: 防御力
        ///15006: 防御力百分比
        ///15007: 元素精通
        ///15008: 火元素伤害加成
        ///15009: 雷元素伤害加成
        ///15010: 冰元素伤害加成
        ///15011: 水元素伤害加成
        ///15012: 风元素伤害加成
        ///15013: 岩元素伤害加成 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ArtifactMainAttribution {
            get {
                return ResourceManager.GetString("ArtifactMainAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空之杯,死之羽,理之冠,生之花,时之沙 的本地化字符串。
        /// </summary>
        internal static string ArtifactPartLabels {
            get {
                return ResourceManager.GetString("ArtifactPartLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 101021: 生命值+24
        ///101022: 生命值+30
        ///201021: 生命值+50
        ///201022: 生命值+61
        ///201023: 生命值+72
        ///301021: 生命值+100
        ///301022: 生命值+115
        ///301023: 生命值+129
        ///301024: 生命值+143
        ///401021: 生命值+167
        ///401022: 生命值+191
        ///401023: 生命值+215
        ///401024: 生命值+239
        ///501021: 生命值+209
        ///501022: 生命值+239
        ///501023: 生命值+269
        ///501024: 生命值+299
        ///101031: 生命值百分比+1.2%
        ///101032: 生命值百分比+1.5%
        ///201031: 生命值百分比+1.6%
        ///201032: 生命值百分比+2.0%
        ///201033: 生命值百分比+2.3%
        ///301031: 生命值百分比+2.4%
        ///301032: 生命值百分比+2.8%
        ///301033: 生命值百分比+3.2%
        ///301034: 生命值百分比+3.5%
        ///401031: 生命值百分比+3.3%
        ///401032: 生命值百分比+3.7%
        ///401033: 生命值百分比+4.2%
        ///40103 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ArtifactSubAttribution {
            get {
                return ResourceManager.GetString("ArtifactSubAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除？ 的本地化字符串。
        /// </summary>
        internal static string AskConfirmDeletion {
            get {
                return ResourceManager.GetString("AskConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1002: 神里绫华
        ///1003: 琴
        ///1005: 空
        ///1006: 丽莎
        ///1007: 荧
        ///1014: 芭芭拉
        ///1015: 凯亚
        ///1016: 迪卢克
        ///1020: 雷泽
        ///1021: 安柏
        ///1022: 温迪
        ///1023: 香菱
        ///1024: 北斗
        ///1025: 行秋
        ///1026: 魈
        ///1027: 凝光
        ///1029: 可莉
        ///1030: 钟离
        ///1031: 菲谢尔
        ///1032: 班尼特
        ///1033: 达达利亚
        ///1034: 诺艾尔
        ///1035: 七七
        ///1036: 重云
        ///1037: 甘雨
        ///1038: 阿贝多
        ///1039: 迪奥娜
        ///1041: 莫娜
        ///1042: 刻晴
        ///1043: 砂糖
        ///1044: 辛焱
        ///1045: 罗莎莉亚
        ///1046: 胡桃
        ///1047: 枫原万叶
        ///1048: 烟绯
        ///1049: 宵宫
        ///1050: 托马
        ///1051: 优菈
        ///1052: 雷电将军
        ///1053: 早柚
        ///1054: 珊瑚宫心海
        ///1055: 五郎
        ///1056: 九条裟罗
        ///1057: 荒泷一斗
        ///1058: 八重神子
        ///1059: 鹿野院平藏
        ///1060: 夜兰
        ///1062: 埃洛伊
        ///1063: 申鹤
        ///1064: 云堇
        ///1065: 久岐忍
        ///1066: 神里绫人
        ///1067: 柯莱
        ///1068:  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1001:purple
        ///1002:yellow
        ///1003:yellow
        ///1005:yellow
        ///1006:purple
        ///1007:yellow
        ///1014:purple
        ///1015:purple
        ///1016:yellow
        ///1020:purple
        ///1021:purple
        ///1022:yellow
        ///1023:purple
        ///1024:purple
        ///1025:purple
        ///1026:yellow
        ///1027:purple
        ///1029:yellow
        ///1030:yellow
        ///1031:purple
        ///1032:purple
        ///1033:yellow
        ///1034:purple
        ///1035:yellow
        ///1036:purple
        ///1037:yellow
        ///1038:yellow
        ///1039:purple
        ///1041:yellow
        ///1042:yellow
        ///1043:purple
        ///1044:purple
        ///1045:purple
        ///1046:yellow
        ///1047:yellow
        ///1048:purple
        ///1049:yellow
        ///1050:purple
        ///1051:yellow
        ///1052:yellow
        ///1053:purple
        ///1054:yellow
        ///1055:pur [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AvatarColor {
            get {
                return ResourceManager.GetString("AvatarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] AvatarStats {
            get {
                object obj = ResourceManager.GetObject("AvatarStats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 浏览器打开失败，你可以通过以下链接手动访问： 的本地化字符串。
        /// </summary>
        internal static string BrowserOpenFailedTip {
            get {
                return ResourceManager.GetString("BrowserOpenFailedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查到新版本 的本地化字符串。
        /// </summary>
        internal static string CheckToNewVersion {
            get {
                return ResourceManager.GetString("CheckToNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无,晴天,多云,雨天,雷暴,雪天,雾天 的本地化字符串。
        /// </summary>
        internal static string ClimateType {
            get {
                return ResourceManager.GetString("ClimateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒后可重发 的本地化字符串。
        /// </summary>
        internal static string CodeResendTip {
            get {
                return ResourceManager.GetString("CodeResendTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送中... 的本地化字符串。
        /// </summary>
        internal static string CodeSending {
            get {
                return ResourceManager.GetString("CodeSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令内容不能为空 的本地化字符串。
        /// </summary>
        internal static string CommandContentCannotBeEmpty {
            get {
                return ResourceManager.GetString("CommandContentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到该命令 的本地化字符串。
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令标签不能为空 的本地化字符串。
        /// </summary>
        internal static string CommandTagCannotBeEmpty {
            get {
                return ResourceManager.GetString("CommandTagCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现在你可以远程执行命令了哦！ 的本地化字符串。
        /// </summary>
        internal static string ConnectedTip {
            get {
                return ResourceManager.GetString("ConnectedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上帝模式
        ////prop god on
        ///上帝模式(old)
        ////godmode
        ///不消耗体力
        ////prop ns on
        ///不消耗体力(old)
        ////ns
        ///不使用元素能量
        ////prop ue on
        ///冒险等阶升到60级
        ////give 102 x1880200
        ///设置世界等级8
        ////prop wl 8
        ///一键解锁深渊12层
        ////prop ut 12
        ///设置纪行等级50
        ////prop bp 50
        ///设置好感等级10
        ////setfetterlevel 10
        ///回血
        ////h
        ///自杀
        ////kill 0
        ///全队充能1
        ////spawn 2008 25
        ///全队充能2
        ////give 2008 25
        ///查看坐标
        ////pos
        ///获取全部物品
        ////give all x9999 lv90 c6 r5
        ///一万纠缠
        ////give 223 x10000
        ///一万相遇
        ////give 224 x10000
        ///十万原石
        ////give 201 x100000
        ///千万摩拉
        ////give 202 x10000000
        ///重载配置
        ////reload
        ///重登
        ////kick
        ///清空当前角色命之座(需重登)
        ////resetconst
        ///清空全部角色命之座(需重登)
        ////resetconst all
        ///清空背包
        ////clear all
        ///清空武器
        ////clear w [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CustomCommands {
            get {
                return ResourceManager.GetString("CustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 007: 初行者推荐祈愿
        ///008: 奔行世间
        ///009: 杯装之诗
        ///010: 黎明巡礼
        ///011: 南风之眷
        ///012: 靖妖傩舞
        ///013: 神铸赋形
        ///015: 闪焰的驻足
        ///016: 初行者推荐祈愿
        ///017: 奔行世间
        ///018: 闪焰的驻足
        ///019: 杯装之诗
        ///020: 神铸赋形
        ///021: 神铸赋形
        ///022: 奔行世间
        ///023: 暂别冬都
        ///024: 陵薮市朝
        ///027: 深秘之息
        ///028: 浮生孰来
        ///031: 烟火之邀
        ///032: 鱼龙灯昼
        ///033: 赤团开时
        ///036: 杯装之诗
        ///037: 暂别冬都
        ///040: 陵薮市朝
        ///041: 浪涌之瞬
        ///045: 叶落风随
        ///048: 白鹭之庭
        ///049: 焰色天河
        ///052: 影寂天下人
        ///053: 浮岳虹珠
        ///061: 鬼门斗宴
        ///065: 出尘入世
        ///071: 华紫樱绯
        ///076: 苍流踏花
        ///081: 素霓伣天
        /// 的本地化字符串。
        /// </summary>
        internal static string GachaBennerPrefab {
            get {
                return ResourceManager.GetString("GachaBennerPrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 70220001: 草堆
        ///70220002: 草堆
        ///70220003: 藤蔓堆 踩到会伤人
        ///70220004: 火花 踩到会飞起来爆炸
        ///70220005: 炸药桶
        ///70220006: 石柱子
        ///70220007: 大石堆
        ///70220008: 小石堆
        ///70220009: 小石堆
        ///70220010: 水石 破坏后喷水气
        ///70220011: 风石 破坏后有上升气流
        ///70220012: 风石
        ///70220013: 木箱
        ///70220014: 木桶
        ///70220015: 方形捆草堆
        ///70220016: 圆型捆草堆
        ///70220017: 木材堆
        ///70220018: 石柱子
        ///70220019: 石柱子
        ///70220020: 草藤蔓 碰到会伤人
        ///70220021: 大石头
        ///70220022: 小草堆
        ///70220023: 大草堆
        ///70220024: 大石堆
        ///70220025: 草堆
        ///70220026: 木箱
        ///70220027: 大石堆
        ///70220028: 锤 无法清掉 踩到有伤害
        ///70220029: 大金板 无法清掉
        ///70220030: 防护罩 无法清掉
        ///70220031: 火台 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Gadget {
            get {
                return ResourceManager.GetString("Gadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功! 的本地化字符串。
        /// </summary>
        internal static string GOODImportSuccess {
            get {
                return ResourceManager.GetString("GOODImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否导入  的本地化字符串。
        /// </summary>
        internal static string GOODImportText {
            get {
                return ResourceManager.GetString("GOODImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入GOOD档案 的本地化字符串。
        /// </summary>
        internal static string GOODImportTitle {
            get {
                return ResourceManager.GetString("GOODImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon IconGrasscutter {
            get {
                object obj = ResourceManager.GetObject("IconGrasscutter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgHome {
            get {
                object obj = ResourceManager.GetObject("ImgHome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgIconGrasscutter {
            get {
                object obj = ResourceManager.GetObject("ImgIconGrasscutter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgSupport {
            get {
                object obj = ResourceManager.GetObject("ImgSupport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 101: 角色经验
        ///102: 冒险阅历
        ///103: 星尘
        ///104: 星辉
        ///105: 好感经验
        ///106: 原粹树脂
        ///107: 传说钥匙
        ///108: (test)天体推演
        ///109: 熄星能量
        ///110: 熄星精粹
        ///111: 微光精粹
        ///112: 温暖精粹
        ///113: 奇迹精粹
        ///114: 铁钱
        ///115: 平安玉符
        ///116: 节庆热度
        ///117: 奇术符
        ///118: 庆典巡回券
        ///119: 奇趣协力券
        ///120: 纯水真心
        ///121: 信任值
        ///122: 碎果数据
        ///123: 迷踪币
        ///124: 亮闪闪的漂流物
        ///125: 迷你「羽球」
        ///126: 神秘齿轮
        ///127: 鸣雷霰子
        ///128: 鸣雷纯晶
        ///129: 弈棋术经验
        ///130: 灵妙玉符
        ///131: 逐月节节庆热度
        ///132: 残悴之式札
        ///133: 虚损之拓本
        ///134: 朽裂之庚牌
        ///135: 踏雪章
        ///136: 克险章
        ///137: 逢福玉符
        ///138: 完璧玉符
        ///139: 降魔玉符
        ///140: 幽蕴砺石
        ///142: 战策碎珀
        ///143: 巧思手记(未知id)
        ///144: 随想草稿(未知id)
        ///201: 原石
        ///202: 摩拉
        ///203: 创世结晶
        ///204: 洞天宝钱
        ///210: 原粹精珀（废弃）
        ///211: 原粹树脂（废 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20010101: 草史莱姆
        ///20010201: 大型草史莱姆
        ///20010202: 大型草史莱姆
        ///20010301: 风史莱姆
        ///20010302: 风史莱姆
        ///20010401: 大型风史莱姆
        ///20010402: 大型风史莱姆
        ///20010403: 大型风史莱姆
        ///20010501: 雷史莱姆
        ///20010502: 雷史莱姆
        ///20010601: 大型雷史莱姆
        ///20010602: 大型雷史莱姆
        ///20010604: 大型雷史莱姆
        ///20010701: 变异雷史莱姆
        ///20010702: 变异雷史莱姆
        ///20010703: 变异雷史莱姆
        ///20010801: 冰史莱姆
        ///20010802: 冰史莱姆
        ///20010803: 冰史莱姆
        ///20010901: 大型冰史莱姆
        ///20010902: 大型冰史莱姆
        ///20010903: 大型冰史莱姆
        ///20010904: 大型冰史莱姆
        ///20011001: 水史莱姆
        ///20011002: 水史莱姆
        ///20011101: 大型水史莱姆
        ///20011102: 大型水史莱姆
        ///20011103: 大型水史莱姆
        ///20011201: 火史莱姆
        ///20011202: 火史莱姆
        ///20011203: 火史莱姆
        ///20011301: 大 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Monster {
            get {
                return ResourceManager.GetString("Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本名：{0}
        ///更新时间：{1}
        ///更新内容：
        ///{2}
        ///--------------------------------------------
        ///是否查看更新？选择否将不再提醒该版本。
        ///（更新没指向本项目的release，最好别更新）
        ///     的本地化字符串。
        /// </summary>
        internal static string NewVersionInfo {
            get {
                return ResourceManager.GetString("NewVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1: (test)蒙德城主$UNRELEASED
        ///2: (test)哥哥$UNRELEASED
        ///3: (test)妹妹$UNRELEASED
        ///4: (test)塔主$UNRELEASED
        ///5: (test)仆人$UNRELEASED
        ///6: (test)东北村长$UNRELEASED
        ///7: (test)西北村长$UNRELEASED
        ///8: (test)西南村长$UNRELEASED
        ///9: (test)正南村长$UNRELEASED
        ///10: (test)晖哥$UNRELEASED
        ///11: (test)果酱$UNRELEASED
        ///12: (test)汪汪1$UNRELEASED
        ///13: (test)汪汪2$UNRELEASED
        ///14: (test)汪汪3$UNRELEASED
        ///15: (test)汪汪4$UNRELEASED
        ///21: (test)卫兵$UNRELEASED
        ///22: (test)卫兵$UNRELEASED
        ///23: (test)卫兵$UNRELEASED
        ///24: (test)卫兵$UNRELEASED
        ///25: (test)路人$UNRELEASED
        ///26: (test)路人$UNRELEASED
        ///30: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string NPC {
            get {
                return ResourceManager.GetString("NPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. 填写正确的UID\n2. 向玩家发送验证码\n3. 输入正确的验证码\n4. 连接\n5. 享受 的本地化字符串。
        /// </summary>
        internal static string OpenCommandHelp {
            get {
                return ResourceManager.GetString("OpenCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要设置的权限不能为空！ 的本地化字符串。
        /// </summary>
        internal static string PermissionCannotBeEmpty {
            get {
                return ResourceManager.GetString("PermissionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *
        ///player.*
        ///player.**
        ///server.*
        ///server.**
        ///player.changescene
        ///player.clear
        ///player.enterdungeon
        ///player.enterdungeon.others
        ///player.give
        ///player.give.others
        ///player.godmode
        ///player.heal
        ///player.heal.others
        ///player.killcharacter
        ///player.killcharacter.others
        ///player.quest
        ///player.quest.others
        ///player.resetconstellation
        ///player.resetconstellation.others
        ///player.setfetterlevel
        ///player.setfetterlevel.others
        ///player.setprop
        ///player.setprop.others
        ///player.setstats
        ///player.setstats.others
        ///player.settalent
        ///player.settalent.others
        ///player. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询服务端状态失败： 的本地化字符串。
        /// </summary>
        internal static string QueryServerStatusFailed {
            get {
                return ResourceManager.GetString("QueryServerStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7300101: 森林书 - 林中的奇遇 - 森林的孩子 $BETA
        ///7300201: 森林书 - 林中的奇遇 - 远足 $BETA
        ///7300301: 森林书 - 林中的奇遇 - 迷失的孩子 $BETA
        ///7300506: 正法炬书 - (test)织梦之森其一 $UNRELEASED $BETA
        ///7300606: 正法炬书 - (test)织梦之森其二 $UNRELEASED $BETA
        ///7300706: 正法炬书 - (test)织梦之森其三 $UNRELEASED $BETA
        ///7300801: 正法炬书 - (test)冲击！颠倒织梦！ $UNRELEASED $BETA
        ///7301406: 水天供书 -  ？？？ $BETA
        ///7301501: 水天供书 - 忿怒的铁块 $BETA
        ///7301601: 水天供书 - 沉睡的根系 $BETA
        ///7301701: 水天供书 - 膏腴土地下的唤雨之曲 $BETA
        ///7301801: 水天供书 - 石头的记忆 $BETA
        ///7301901: 愿为一炊之梦 - 料理是快乐的回忆 $BETA
        ///7302001: 愿为一炊之梦 - 料理是自然的风味 $BETA
        ///7302101: 愿 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Quest {
            get {
                return ResourceManager.GetString("Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先连接到支持[OpenCommand]的服务器 的本地化字符串。
        /// </summary>
        internal static string RequireOpenCommandTip {
            get {
                return ResourceManager.GetString("RequireOpenCommandTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认将自定义命令恢复到默认值？ 的本地化字符串。
        /// </summary>
        internal static string RestoreCustomCommands {
            get {
                return ResourceManager.GetString("RestoreCustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1: BigWorld_LevelStreaming
        ///2: BigWorld_LevelStreaming
        ///3: 提瓦特
        ///4: 金苹果群岛(1.6)
        ///5: 渊下宫
        ///6: 层岩巨渊·地下矿区
        ///7: 三界路飨祭
        ///9: 金苹果群岛(2.8)
        ///1001: 移动平台性能测试(test)
        ///1002: ClimbTest2
        ///1003: TheBigWorld
        ///1004: Knight_Inside_Test
        ///1005: ChurchSteal
        ///1006: 密林、废墟与龙之泪
        ///1008: ChurchLobby
        ///1009: AngelShare
        ///1011: 角色战斗测试(test)
        ///1013: SneakAdvancedTest
        ///1015: 飞翔是勇气的奖励
        ///1016: 飞翔是勇气的奖励
        ///1017: 壶中天
        ///1018: Chateau
        ///1019: 洞天云海地城玩法测试(test)
        ///1023: Level_Yurenzhong
        ///1024: 黑夜循环地城(test)
        ///1030: TestIntercept_LiYue
        ///1031: 爬塔丘丘人模板(test)
        ///1032: 云海白盒测试(test)
        ///1033: Indoor_Ly_B [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载设置时异常： 的本地化字符串。
        /// </summary>
        internal static string SettingLoadError {
            get {
                return ResourceManager.GetString("SettingLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置时异常： 的本地化字符串。
        /// </summary>
        internal static string SettingSaveError {
            get {
                return ResourceManager.GetString("SettingSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token不能为空 的本地化字符串。
        /// </summary>
        internal static string TokenCannotBeEmpty {
            get {
                return ResourceManager.GetString("TokenCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已从缓存中恢复Token 的本地化字符串。
        /// </summary>
        internal static string TokenRestoredFromCache {
            get {
                return ResourceManager.GetString("TokenRestoredFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空！ 的本地化字符串。
        /// </summary>
        internal static string UsernameCannotBeEmpty {
            get {
                return ResourceManager.GetString("UsernameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10002: (test)穿模测试
        ///10003: (test)穿模测试
        ///10004: (test)穿模测试
        ///10005: (test)穿模测试
        ///10006: (test)穿模测试
        ///10008: (test)穿模测试
        ///11101: 无锋剑
        ///11201: 银剑
        ///11301: 冷刃
        ///11302: 黎明神剑
        ///11303: 旅行剑
        ///11304: 暗铁剑
        ///11305: 吃虎鱼刀
        ///11306: 飞天御剑
        ///11401: 西风剑
        ///11402: 笛剑
        ///11403: 祭礼剑
        ///11404: 宗室长剑
        ///11405: 匣里龙吟
        ///11406: 试作斩岩
        ///11407: 铁蜂刺
        ///11408: 黑岩长剑
        ///11409: 黑剑
        ///11410: 暗巷闪光
        ///11412: 降临之剑
        ///11413: 腐殖之剑
        ///11414: 天目影打刀
        ///11415: 辰砂之纺锤
        ///11416: 笼钓瓶一心
        ///11417: 原木刀
        ///11419: 「一心传」名刀
        ///11420: 「一心传」名刀
        ///11421: 「一心传」名刀
        ///11501: 风鹰剑
        ///11502: 天空之刃
        ///11503: 苍古自由之誓
        ///11504: 斫峰之刃
        ///11505: 磐岩结绿
        ///11507: 凭虚
        ///11509: 雾切之回光 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11301:blue
        ///11302:blue
        ///11303:blue
        ///11304:blue
        ///11305:blue
        ///11306:blue
        ///11401:purple
        ///11402:purple
        ///11403:purple
        ///11404:purple
        ///11405:purple
        ///11406:purple
        ///11407:purple
        ///11408:purple
        ///11409:purple
        ///11410:purple
        ///11411:purple
        ///11412:purple
        ///11413:purple
        ///11414:purple
        ///11415:purple
        ///11501:yellow
        ///11502:yellow
        ///11503:yellow
        ///11504:yellow
        ///11505:yellow
        ///11506:yellow
        ///11507:yellow
        ///11508:yellow
        ///11509:yellow
        ///11510:yellow
        ///12301:blue
        ///12302:blue
        ///12303:blue
        ///12304:blue
        ///12305:blue
        ///12306:blue
        ///12401:purple
        ///12402:purple
        ///12403:purple
        ///12404:purple
        ///124 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WeaponColor {
            get {
                return ResourceManager.GetString("WeaponColor", resourceCulture);
            }
        }
    }
}
